### PR TITLE
Switch SimpleAjax helper extension

### PR DESCRIPTION
**Pull request by richardhj**
## Description

Hotfix. Discussion and error see #18.

## Checklist
- [x] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] Created tests, if possible
- [ ] All tests passing
- [x] Extended the README / documentation, if necessary
- [x] Added myself to the `@authors` in touched PHP files
- [ ] Checked the changes with phpcq and introduced no new issues

### CODE REVIEW

**Comment by richardhj** [comment]
I need to tag richardhj/contao-simple-ajax@5358218e7133d8cb2d3c90595fe9d2aebc61771b beforehand.

**Comment by zonky2** [comment]
Hi @richardhj, with this fix the rating doesn't work because, Contao check the request token...

we can disable the tocken at backend or use

```diff
// Initialize the Contao framework
define('TL_MODE', 'FE');
+define ('BYPASS_TOKEN_CHECK', true);
...
``` 

at `SimpleAjaxFrontend.php` ... 

Maybe we will find a solution where we can keep the request token?

**Comment by richardhj** [comment]
Yep, we do not bypass the request token but add it as a request parameter.
Thanks @zonky2

**Comment by zonky2** [comment]
RTT

**Pull request merged**
